/*
 * Designed and developed by Duckie Team 2023.
 *
 * Licensed under the MIT.
 * Please see full license: https://github.com/duckie-team/quack-quack-android/blob/main/LICENSE
 */

package team.duckie.quackquack.util.backend.kotlinpoet

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec

public fun getGeneratedFileComment(source: String): String =
  "This file was automatically generated by $source.\nDo not modify it manually."

// https://detekt.dev/docs/introduction/suppressing-rules
// https://pinterest.github.io/ktlint/0.50.0/faq/#how-do-i-suppress-errors-for-a-lineblockfile
public fun FileSpec.Builder.addSuppressionAnnotation(): FileSpec.Builder =
  addAnnotation(
    AnnotationSpec
      .builder(Suppress::class)
      .addMember("%S, %S", "detekt:all", "ktlint")
      .useSiteTarget(AnnotationSpec.UseSiteTarget.FILE)
      .build(),
  )

public fun FileSpec.Builder.addAnnotations(vararg annotations: AnnotationSpec): FileSpec.Builder =
  addAnnotations(annotations.asList())

public fun FunSpec.Builder.addAnnotations(vararg annotations: ClassName): FunSpec.Builder =
  addAnnotations(annotations.asList())

public fun FunSpec.Builder.addAnnotations(annotations: List<ClassName>): FunSpec.Builder =
  apply { annotations.forEach(::addAnnotation) }

public fun FileSpec.Builder.addFunctions(vararg functions: FunSpec): FileSpec.Builder =
  addFunctions(functions.asList())

public fun FileSpec.Builder.addFunctions(functions: List<FunSpec>): FileSpec.Builder =
  apply { functions.forEach(::addFunction) }
