/*
 * Designed and developed by Duckie Team 2023.
 *
 * Licensed under the MIT.
 * Please see full license: https://github.com/duckie-team/quack-quack-android/blob/main/LICENSE
 */

package team.duckie.quackquack.util.backend

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec

public fun getGeneratedFileComment(source: String): String =
  "This file was automatically generated by $source.\nDo not modify it manually."

public const val FormatterOffComment: String = "\n@formatter:off"

public val SuppressAnnotation: AnnotationSpec = AnnotationSpec
  .builder(Suppress::class)
  .addMember(
    // FIXME: how to suppress all lints? (detekt, compose, ... etc)
    "%S, %S, %S, %S, %S, %S, %S, %S, %S, %S, %S, %S, %S, %S, %S",
    "NoConsecutiveBlankLines",
    "PackageDirectoryMismatch",
    "Wrapping",
    "TrailingCommaOnCallSite",
    "ArgumentListWrapping",
    "RedundantVisibilityModifier",
    "UnusedImport",
    "NoUnusedImports",
    "SpacingAroundParens",
    "Indentation",
    "NoUnitReturn",
    "RedundantUnitReturnType",
    "ModifierParameter",
    "KDocUnresolvedReference",
    "ktlint",
  )
  .useSiteTarget(AnnotationSpec.UseSiteTarget.FILE)
  .build()

public fun FileSpec.Builder.addAnnotations(vararg annotations: AnnotationSpec): FileSpec.Builder =
  addAnnotations(annotations.asList())

public fun FileSpec.Builder.addAnnotations(annotations: List<AnnotationSpec>): FileSpec.Builder =
  apply { annotations.forEach(::addAnnotation) }

public fun FunSpec.Builder.addAnnotations(vararg annotations: ClassName): FunSpec.Builder =
  addAnnotations(annotations.asList())

public fun FunSpec.Builder.addAnnotations(annotations: List<ClassName>): FunSpec.Builder =
  apply { annotations.forEach(::addAnnotation) }

public fun FileSpec.Builder.addFunctions(vararg functions: FunSpec): FileSpec.Builder =
  addFunctions(functions.asList())

public fun FileSpec.Builder.addFunctions(functions: List<FunSpec>): FileSpec.Builder =
  apply { functions.forEach(::addFunction) }
