// This file was automatically generated by aide-processor.
// Do not modify it arbitrarily.
// @formatter:off
@file:Suppress("NoConsecutiveBlankLines", "PackageDirectoryMismatch", "Wrapping",
    "TrailingCommaOnCallSite", "ArgumentListWrapping", "ktlint")

import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlin.collections.Map

internal val aideModifiers: Map<String, List<String>> = run {
  val aide = mutableMapOf<String, List<String>>()

  aide["text"] = listOf("span", "highlight")
  aide["_span"] = emptyList()
  aide["_highlight"] = emptyList()

  aide
}

