// This file was automatically generated by core-aide-processor.
// Do not modify it arbitrarily.
// @formatter:off
@file:Suppress("NoConsecutiveBlankLines", "PackageDirectoryMismatch", "Wrapping",
    "TrailingCommaOnCallSite", "ArgumentListWrapping", "ktlint")

import kotlin.String
import kotlin.Suppress
import kotlin.collections.Map

internal val quackComponents: Map<String, String> = run {
  val aide = mutableMapOf<String, String>()

  aide["QuackBody1"] = "text"
  aide["QuackBody2"] = "text"
  aide["QuackBody3"] = "text"
  aide["QuackHeadLine1"] = "text"
  aide["QuackHeadLine2"] = "text"
  aide["QuackLarge1"] = "text"
  aide["QuackSubtitle"] = "text"
  aide["QuackSubtitle2"] = "text"
  aide["QuackTitle1"] = "text"
  aide["QuackTitle2"] = "text"
  aide["QuackText"] = "text"

  aide
}

