// This file was automatically generated by aide-processor.
// Do not modify it arbitrarily.
// @formatter:off
@file:Suppress("NoConsecutiveBlankLines", "PackageDirectoryMismatch", "Wrapping",
    "TrailingCommaOnCallSite", "ArgumentListWrapping", "ktlint")

import kotlin.String
import kotlin.Suppress
import kotlin.collections.Map

internal val quackComponents: Map<String, String> = run {
  val aide = mutableMapOf<String, String>()

  aide["QuackButton"] = "button"
  aide["QuackBaseButton"] = "button"

  aide
}

