// This file was automatically generated by aide-processor.
// Do not modify it manually.
// @formatter:off
@file:Suppress("NoConsecutiveBlankLines", "PackageDirectoryMismatch", "Wrapping",
    "TrailingCommaOnCallSite", "ArgumentListWrapping", "RedundantVisibilityModifier",
    "UnusedImport", "NoUnusedImports", "SpacingAroundParens", "ktlint")

internal val aideModifiers: Map<String, List<String>> = run {
  val aide = mutableMapOf<String, List<String>>()

  aide["button"] = listOf("icons")
  aide["_icons"] = emptyList()

  aide["text"] = listOf("span", "highlight")
  aide["_span"] = emptyList()
  aide["_highlight"] = emptyList()

  aide
}

