// This file was automatically generated by aide-processor.
// Do not modify it manually.
// @formatter:off
@file:Suppress("NoConsecutiveBlankLines", "PackageDirectoryMismatch", "Wrapping",
    "TrailingCommaOnCallSite", "ArgumentListWrapping", "RedundantVisibilityModifier",
    "UnusedImport", "NoUnusedImports", "SpacingAroundParens", "Indentation", "NoUnitReturn",
    "RedundantUnitReturnType", "ModifierParameter", "KDocUnresolvedReference", "NoTrailingSpaces",
    "NoMultipleSpaces", "ktlint")

import kotlin.String
import kotlin.Suppress
import kotlin.collections.Map

internal val quackComponents: Map<String, String> = run {
  val aide = mutableMapOf<String, String>()

  aide["QuackButton"] = "button"
  aide["QuackBaseButton"] = "button"
  aide["QuackPrimaryLargeButton"] = "button"
  aide["QuackSecondaryLargeButton"] = "button"
  aide["QuackMediumButton"] = "button"
  aide["QuackPrimaryFilledSmallButton"] = "button"
  aide["QuackPrimaryOutlinedSmallButton"] = "button"
  aide["QuackPrimaryOutlinedRoundSmallButton"] = "button"
  aide["QuackSecondarySmallButton"] = "button"
  aide["QuackSecondaryRoundSmallButton"] = "button"

  aide["QuackOutlinedTag"] = "tag"
  aide["QuackFilledTag"] = "tag"
  aide["QuackGrayscaleFlatTag"] = "tag"
  aide["QuackGrayscaleOutlinedTag"] = "tag"
  aide["QuackTag"] = "tag"
  aide["QuackBaseTag"] = "tag"

  aide["QuackBody1"] = "text"
  aide["QuackBody2"] = "text"
  aide["QuackBody3"] = "text"
  aide["QuackHeadLine1"] = "text"
  aide["QuackHeadLine2"] = "text"
  aide["QuackLarge1"] = "text"
  aide["QuackSubtitle"] = "text"
  aide["QuackSubtitle2"] = "text"
  aide["QuackTitle1"] = "text"
  aide["QuackTitle2"] = "text"
  aide["QuackText"] = "text"

  aide
}

