// This file was automatically generated by aide-processor.
// Do not modify it manually.
// @formatter:off
@file:Suppress("NoConsecutiveBlankLines", "PackageDirectoryMismatch", "Wrapping",
    "TrailingCommaOnCallSite", "ArgumentListWrapping", "RedundantVisibilityModifier",
    "UnusedImport", "NoUnusedImports", "SpacingAroundParens", "Indentation", "NoUnitReturn",
    "RedundantUnitReturnType", "ModifierParameter", "KDocUnresolvedReference", "NoTrailingSpaces",
    "NoMultipleSpaces", "ktlint")

import kotlin.String
import kotlin.Suppress
import kotlin.collections.Map

internal val quackComponents: Map<String, String> = run {
  val aide = mutableMapOf<String, String>()

  aide["QuackButton"] = "button"
  aide["QuackBaseButton"] = "button"
  aide["QuackPrimaryLargeButton"] = "button"
  aide["QuackSecondaryLargeButton"] = "button"
  aide["QuackMediumButton"] = "button"
  aide["QuackPrimaryFilledSmallButton"] = "button"
  aide["QuackPrimaryOutlinedSmallButton"] = "button"
  aide["QuackPrimaryOutlinedRoundSmallButton"] = "button"
  aide["QuackSecondarySmallButton"] = "button"
  aide["QuackSecondaryRoundSmallButton"] = "button"

  aide["QuackIcon"] = "icon"
  aide["QuackAreaIcon"] = "icon"
  aide["QuackArrowBackIcon"] = "icon"
  aide["QuackArrowDownIcon"] = "icon"
  aide["QuackArrowRightIcon"] = "icon"
  aide["QuackArrowSendIcon"] = "icon"
  aide["QuackBadgeIcon"] = "icon"
  aide["QuackBookmarkIcon"] = "icon"
  aide["QuackBuyIcon"] = "icon"
  aide["QuackCameraIcon"] = "icon"
  aide["QuackCheckIcon"] = "icon"
  aide["QuackCloseIcon"] = "icon"
  aide["QuackCommentIcon"] = "icon"
  aide["QuackDeleteIcon"] = "icon"
  aide["QuackDeleteBgIcon"] = "icon"
  aide["QuackDmIcon"] = "icon"
  aide["QuackFeedIcon"] = "icon"
  aide["QuackFilledBookmarkIcon"] = "icon"
  aide["QuackFilledHeartIcon"] = "icon"
  aide["QuackFilledProfileIcon"] = "icon"
  aide["QuackFilterIcon"] = "icon"
  aide["QuackGalleryIcon"] = "icon"
  aide["QuackHeartIcon"] = "icon"
  aide["QuackImageIcon"] = "icon"
  aide["QuackImageEditIcon"] = "icon"
  aide["QuackImageEditBgIcon"] = "icon"
  aide["QuackMarketPriceIcon"] = "icon"
  aide["QuackMoreIcon"] = "icon"
  aide["QuackNoticeAddIcon"] = "icon"
  aide["QuackPlaceIcon"] = "icon"
  aide["QuackPlusIcon"] = "icon"
  aide["QuackProfileIcon"] = "icon"
  aide["QuackSearchIcon"] = "icon"
  aide["QuackSellIcon"] = "icon"
  aide["QuackSettingIcon"] = "icon"
  aide["QuackShareIcon"] = "icon"
  aide["QuackTagIcon"] = "icon"
  aide["QuackTextLogoIcon"] = "icon"
  aide["QuackWhiteHeartIcon"] = "icon"
  aide["QuackWonIcon"] = "icon"

  aide["QuackImage"] = "image"

  aide["QuackOutlinedTag"] = "tag"
  aide["QuackFilledTag"] = "tag"
  aide["QuackGrayscaleFlatTag"] = "tag"
  aide["QuackGrayscaleOutlinedTag"] = "tag"
  aide["QuackTag"] = "tag"
  aide["QuackBaseTag"] = "tag"

  aide["QuackBody1"] = "text"
  aide["QuackBody2"] = "text"
  aide["QuackBody3"] = "text"
  aide["QuackHeadLine1"] = "text"
  aide["QuackHeadLine2"] = "text"
  aide["QuackLarge1"] = "text"
  aide["QuackSubtitle"] = "text"
  aide["QuackSubtitle2"] = "text"
  aide["QuackTitle1"] = "text"
  aide["QuackTitle2"] = "text"
  aide["QuackText"] = "text"

  aide
}

