// This file was automatically generated by core-aide-processor.
// Do not modify it arbitrarily.
@file:Suppress("NoConsecutiveBlankLines", "PackageDirectoryMismatch", "ktlint")

import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlin.collections.Map

internal val aideModifiers: Map<String, List<String>> = run {
  val aide = mutableMapOf<String, List<String>>()
  aide["text"] = listOf("span", "highlight")
  // --- START: text Modifiers ---
  aide["span"] = emptyList()
  aide["highlight"] = emptyList()
  // --- END: text Modifiers ---
  aide
}

