// This file was automatically generated by core-aide-processor.
// Do not modify it arbitrarily.
@file:Suppress(
    "NoConsecutiveBlankLines", "PackageDirectoryMismatch", "Wrapping",
    "TrailingCommaOnCallSite", "ArgumentListWrapping", "ktlint"
)

internal val aideModifiers: Map<String, List<String>> = run {
    val aide = mutableMapOf<String, List<String>>()

    aide["text"] = listOf("span", "highlight")
    aide["_span"] = emptyList()
    aide["_highlight"] = emptyList()

    aide
}

