// This file was automatically generated by core-aide-processor.
// Do not modify it arbitrarily.
@file:Suppress("NoConsecutiveBlankLines", "PackageDirectoryMismatch", "Wrapping",
    "TrailingCommaOnCallSite", "ArgumentListWrapping", "ktlint")

import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlin.collections.Map

internal val aideComponents: Map<String, List<String>> = run {
  val aide = mutableMapOf<String, List<String>>()
  aide["text"] = listOf("QuackLarge1", "QuackHeadLine1", "QuackHeadLine2", "QuackTitle1",
      "QuackTitle2", "QuackSubtitle", "QuackSubtitle2", "QuackBody1", "QuackBody2", "QuackBody3")
  aide
}

