// This file was automatically generated by core-aide-processor.
// Do not modify it arbitrarily.
@file:Suppress("NoConsecutiveBlankLines", "PackageDirectoryMismatch", "Wrapping",
    "TrailingCommaOnCallSite", "ArgumentListWrapping", "ktlint")

import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

internal val quackComponents: List<String> = listOf("QuackAnimatedContent",
    "QuackAnimatedVisibility", "QuackLarge1", "QuackHeadLine1", "QuackHeadLine2", "QuackTitle1",
    "QuackTitle2", "QuackSubtitle", "QuackSubtitle2", "QuackBody1", "QuackBody2", "QuackBody3",
    "QuackText", "QuackTheme")
