// This file was automatically generated by core-aide-processor.
// Do not modify it arbitrarily.
@file:Suppress(
    "NoConsecutiveBlankLines", "PackageDirectoryMismatch", "Wrapping",
    "TrailingCommaOnCallSite", "ArgumentListWrapping", "ktlint"
)

internal val quackComponents: Map<String, String> = run {
    val aide = mutableMapOf<String, String>()

    aide["QuackAnimatedContent"] = "QuackAnimatedContent"

    aide["QuackAnimatedVisibility"] = "QuackAnimatedVisibility"

    aide["QuackLarge1"] = "text"
    aide["QuackHeadLine1"] = "text"
    aide["QuackHeadLine2"] = "text"
    aide["QuackTitle1"] = "text"
    aide["QuackTitle2"] = "text"
    aide["QuackSubtitle"] = "text"
    aide["QuackSubtitle2"] = "text"
    aide["QuackBody1"] = "text"
    aide["QuackBody2"] = "text"
    aide["QuackBody3"] = "text"
    aide["QuackText"] = "text"

    aide["QuackTheme"] = "theme"

    aide
}

